# Generated by Django 5.0.3 on 2024-03-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization_code',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Код активации'),
        ),
    ]
