# Generated by Django 5.0.3 on 2024-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization_code',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Код активации'),
        ),
    ]
