# Generated by Django 5.0.3 on 2024-03-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Персональный инвайт-код'),
        ),
        migrations.AddField(
            model_name='user',
            name='someone_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Чужой инвайт-код'),
        ),
    ]
