# Generated by Django 5.0.3 on 2024-03-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_personal_invite_code_user_someone_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization_code',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Код активации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_invite_code',
            field=models.CharField(default='hrZQZh', max_length=6, verbose_name='Персональный инвайт-код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Телефон'),
        ),
    ]
