version: '3.8'

services:
  db:
    image: postgres:16
    container_name:
      postgres
    environment:
      - PGDATA=$DOCKER_PGDATA
      - POSTGRES_USER=$DOCKER_POSTGRES_USER
      - POSTGRES_PASSWORD=$DOCKER_POSTGRES_PASSWORD
      - POSTGRES_DB=$DOCKER_POSTGRES_DB
    ports:
      - '5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    tty: True
    build: .
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
